# Modified jpackage workflow to build for macOS only

 name: Build packages with jpackage (macOS)

 on: [workflow_dispatch]

 jobs:
   build:
    strategy:
      matrix:
        include: 
          - platform: macos-latest
            type: pkg
    container: ${{ matrix.container }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build with Gradle
      if: matrix.container == ''
      uses: gradle/gradle-build-action@v2
      with:
        arguments: jpackage -P git-commit=true -P package=installer mergedJavadoc createChecksums
    - uses: actions/upload-artifact@v3
      with:
        name: jpackage-${{ matrix.type }}
        path: build/dist
        retention-days: 1
